version: "3.3"

services:
  database: 
    image: postgres
    container_name: database_tarefa
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=db_tarefa_user
      - POSTGRES_PASSWORD=Pass102030
      - POSTGRES_DB=db_tarefa
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:alpine
    container_name: redis_tarefa
    ports: 
      - 6379:6379

volumes:
  pgdata:
    driver: local

networks:
  default:
    driver: bridge
